# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: github-action-typescript-template
  description: A template repo for GitHub Actions built in typescript
  homepage: https://cloudposse.com/accelerate
  topics: ""
